### ISSUE TITLE
React-Scripts v4

### ISSUE THREAD

**Issue by darrengeary** [hetjagani/Indeed-Clone#118]
With the current version it is using react-scripts v4 however when I run the application. I was getting an error like this 

> > Uncaught ReferenceError: process is not defined at 
> Object.4043 (<anonymous>:2:13168) at r (<anonymous>:2:306599) at 
> Object.8048 (<anonymous>:2:9496) at r (<anonymous>:2:306599) at 
> Object.8641 (<anonymous>:2:1379) at r (<anonymous>:2:306599) at 
> <anonymous>:2:315627 at <anonymous>:2:324225 at <anonymous>:2:324229 
> at HTMLIFrameElement.e.onload

I updated the react-script version to 5.0.1 in the package.json file but ran into some more errors with pollyfills. The error was like the following but aswelll as buffer there were errors for 'stream' and 'crypto' 

> Module not found: Error: Can't resolve 'buffer' in ...
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.

They were resolved by npm install buffer and npm install stream but crypto was not resolved with a similiar approach.

I am also getting this error since updating to react-scripts v5

> Line 49:25:  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

This can be resolved by adding the following to the rules object of all the relevant eslintrc.json files

> "linebreak-style": ["error", "unix"],

and finally one last error is 

> ERROR in ./node_modules/dotenv/lib/main.js 24:11-24Module not found: Error: Can't resolve 'fs' in '/app/node_modules/dotenv/lib'

Can anyone help me understand what is happening here, Is there an easier option for me to resolve the original error without creating many more?

**Comment by darrengeary** [comment]
Instead of changing react-scripts to v5, you can keep it at v4 and install react-error-overlay v6.0.9 inside your devDependencies.

> npm install react-error-overlay@6.0.9

Regarding 

> Line 49:25: Expected linebreaks to be 'LF' but found 'CRLF' linebreak-style

This can be fixed by the following commands in the root folder.

> git config core.autocrlf false 
> git rm --cached -r . 
> git reset --hard

**Comment by hetjagani** [comment]
Thank you @darrengeary for pointing this out.
